# Use the backend base image
FROM backend_base

# Set entrypoint
ENTRYPOINT ["/usr/local/bin/web.sh"]

# Switch to non-root user
USER appuser

# Expose the application port
EXPOSE 8001

# Run command
CMD ["uvicorn", "config.asgi:application", "--host", "0.0.0.0", "--port", "8001", "--reload"]
